# Generated by Django 5.1.5 on 2026-06-20 12:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_enrollment_enrollment_unique_student_class_when_no_course'),
        ('schools', '0002_school_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillshipAssignment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('weekdays', models.JSONField(blank=True, default=list)),
                ('specific_dates', models.JSONField(blank=True, default=list)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skillship_assignments_created', to=settings.AUTH_USER_MODEL)),
                ('klass', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skillship_assignments', to='academics.class')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skillship_assignments', to='schools.school')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'TEACHER', 'teacher_type': 'SKILLSHIP'}, on_delete=django.db.models.deletion.CASCADE, related_name='skillship_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['teacher', 'is_active'], name='assignments_teacher_e377de_idx'), models.Index(fields=['school', 'is_active'], name='assignments_school__d02188_idx')],
            },
        ),
    ]
