# Generated by Django 5.1.5 on 2026-06-21 07:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
        ('schools', '0002_school_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubAdminGrant',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('can_manage_school', models.BooleanField(default=False)),
                ('can_onboard_students', models.BooleanField(default=False)),
                ('can_onboard_teachers', models.BooleanField(default=False)),
                ('can_approve_quizzes', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subadmin_grants_created', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subadmin_grants', to='schools.school')),
                ('subadmin', models.ForeignKey(limit_choices_to={'role': 'SUB_ADMIN'}, on_delete=django.db.models.deletion.CASCADE, related_name='subadmin_grants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['subadmin', 'is_active'], name='assignments_subadmi_028fa4_idx'), models.Index(fields=['school', 'is_active'], name='assignments_school__e84d4c_idx')],
                'constraints': [models.UniqueConstraint(fields=('subadmin', 'school'), name='uniq_subadmin_school_grant')],
            },
        ),
    ]
