# Generated by Django 5.1.5 on 2026-06-22 18:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_subadmingrant'),
        ('schools', '0002_school_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTeachingLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('subject', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='schools.school')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'TEACHER', 'teacher_type': 'SKILLSHIP'}, on_delete=django.db.models.deletion.CASCADE, related_name='daily_teaching_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['school', 'created_at'], name='assignments_school__f2b8be_idx'), models.Index(fields=['teacher', 'date'], name='assignments_teacher_26a924_idx')],
            },
        ),
    ]
