# Generated by Django 5.1.5 on 2026-06-22 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_dailyteachinglog'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyteachinglog',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyteachinglog',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyteachinglog',
            name='photo',
            field=models.TextField(blank=True),
        ),
    ]
