# Generated by Django 5.1.5 on 2026-06-27 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_dailyteachinglog_latitude_dailyteachinglog_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillshipassignment',
            name='subject',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
