# Generated by Django 5.1.5 on 2026-05-26 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplacelisting',
            name='category',
            field=models.CharField(blank=True, choices=[('ai', 'AI'), ('robotics', 'Robotics'), ('coding', 'Coding'), ('electronics', 'Electronics'), ('iot', 'IoT')], help_text='AI / Robotics / Coding / Electronics / IoT. Drives category badges on the marketing site.', max_length=20),
        ),
        migrations.AddField(
            model_name='marketplacelisting',
            name='class_range',
            field=models.CharField(blank=True, help_text='Target grade band as displayed, e.g. "Class 6-8".', max_length=40),
        ),
        migrations.AddField(
            model_name='marketplacelisting',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], help_text='Beginner / Intermediate / Advanced. Drives the difficulty filter chips.', max_length=15),
        ),
        migrations.AddField(
            model_name='marketplacelisting',
            name='duration_key',
            field=models.CharField(blank=True, choices=[('under-2-hours', 'Under 2 hours'), ('half-day', 'Half day'), ('multi-session', 'Multi-session')], help_text='Bucket used by the duration filter chips.', max_length=20),
        ),
        migrations.AddField(
            model_name='marketplacelisting',
            name='duration_label',
            field=models.CharField(blank=True, help_text='Human-readable label, e.g. "90 minutes" or "3 sessions".', max_length=40),
        ),
        migrations.AddIndex(
            model_name='marketplacelisting',
            index=models.Index(fields=['is_active', 'category'], name='mktpl_active_category_idx'),
        ),
    ]
