# Generated by Django 5.1.5 on 2026-06-18 12:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_bridge', '0003_aijob_college_finder_kind'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoadmapTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('career_slug', models.SlugField(max_length=80)),
                ('career_title', models.CharField(max_length=120)),
                ('grade', models.PositiveSmallIntegerField()),
                ('board', models.CharField(max_length=10)),
                ('detail_json', models.JSONField()),
                ('version', models.PositiveIntegerField(default=1)),
                ('source_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roadmap_templates', to='ai_bridge.aijob')),
            ],
        ),
        migrations.CreateModel(
            name='StudentRoadmap',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('career_slug', models.SlugField(max_length=80)),
                ('career_title', models.CharField(max_length=120)),
                ('grade', models.PositiveSmallIntegerField()),
                ('board', models.CharField(max_length=10)),
                ('is_objective', models.BooleanField(default=False)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_roadmaps', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_roadmaps', to='career.roadmaptemplate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentCareerProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('career_slug', models.SlugField(blank=True, max_length=80)),
                ('career_title', models.CharField(blank=True, max_length=120)),
                ('objective_set_at', models.DateTimeField(blank=True, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='schools.school')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='career_profile', to=settings.AUTH_USER_MODEL)),
                ('active_roadmap', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='career.studentroadmap')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CareerChecklist',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('career_title', models.CharField(max_length=120)),
                ('headline', models.CharField(blank=True, max_length=240)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='schools.school')),
                ('source_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='career_checklists', to='ai_bridge.aijob')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_checklists', to=settings.AUTH_USER_MODEL)),
                ('roadmap', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklists', to='career.studentroadmap')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChecklistTask',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_index', models.PositiveSmallIntegerField()),
                ('due_date', models.DateField()),
                ('title', models.CharField(max_length=200)),
                ('detail', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=40)),
                ('is_done', models.BooleanField(default=False)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='career.careerchecklist')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='schools.school')),
            ],
            options={
                'ordering': ['day_index'],
                'abstract': False,
                'indexes': [models.Index(fields=['school', 'created_at'], name='career_chec_school__d76bfa_idx')],
                'constraints': [models.UniqueConstraint(fields=('checklist', 'day_index'), name='checklist_task_unique_day')],
            },
        ),
        migrations.AddIndex(
            model_name='roadmaptemplate',
            index=models.Index(fields=['career_slug', 'grade', 'board'], name='career_road_career__8427b9_idx'),
        ),
        migrations.AddConstraint(
            model_name='roadmaptemplate',
            constraint=models.UniqueConstraint(fields=('career_slug', 'grade', 'board'), name='roadmap_template_unique_career_grade_board'),
        ),
        migrations.AddIndex(
            model_name='studentroadmap',
            index=models.Index(fields=['school', 'created_at'], name='career_stud_school__c442ca_idx'),
        ),
        migrations.AddIndex(
            model_name='studentroadmap',
            index=models.Index(fields=['student', 'created_at'], name='career_stud_student_f69ddc_idx'),
        ),
        migrations.AddIndex(
            model_name='studentcareerprofile',
            index=models.Index(fields=['school', 'created_at'], name='career_stud_school__bf0f2a_idx'),
        ),
        migrations.AddIndex(
            model_name='careerchecklist',
            index=models.Index(fields=['school', 'created_at'], name='career_care_school__9d8e3a_idx'),
        ),
        migrations.AddIndex(
            model_name='careerchecklist',
            index=models.Index(fields=['student', 'created_at'], name='career_care_student_480375_idx'),
        ),
    ]
