# Generated by Django 5.1.5 on 2026-06-18 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentroadmap',
            name='is_saved',
            field=models.BooleanField(default=False),
        ),
    ]
