# Generated by Django 5.1.5 on 2026-06-13 11:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_enrollment_enrollment_unique_student_class_when_no_course'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamAlert',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('CLASS_TEST', 'Class Test'), ('SEMESTER', 'Semester Exam'), ('ENTRANCE', 'Entrance Exam'), ('OTHER', 'Other')], default='CLASS_TEST', max_length=20)),
                ('mode', models.CharField(choices=[('PHYSICAL', 'Physical'), ('VIRTUAL', 'Virtual')], default='PHYSICAL', max_length=10)),
                ('exam_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('venue', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exam_alerts', to=settings.AUTH_USER_MODEL)),
                ('klass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_alerts', to='academics.class')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='schools.school')),
            ],
            options={
                'ordering': ['exam_date', '-created_at'],
                'indexes': [models.Index(fields=['school', 'exam_date'], name='exam_alerts_school__8089ee_idx'), models.Index(fields=['klass', 'exam_date'], name='exam_alerts_klass_i_a58c7f_idx')],
            },
        ),
    ]
