# Generated by Django 5.1.5 on 2026-06-19 14:19

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('CHARGE', 'Charge (billed to school)'), ('PAYMENT', 'Payment (received from school)')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('occurred_on', models.DateField()),
                ('method', models.CharField(blank=True, choices=[('UPI', 'UPI'), ('BANK', 'Bank Transfer'), ('CASH', 'Cash'), ('CHEQUE', 'Cheque'), ('CARD', 'Card'), ('OTHER', 'Other')], max_length=10)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_entries_created', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='schools.school')),
            ],
            options={
                'verbose_name_plural': 'Billing entries',
                'ordering': ['-occurred_on', '-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['school', 'created_at'], name='billing_bil_school__7245a1_idx'), models.Index(fields=['school', 'kind'], name='billing_bil_school__461cfc_idx'), models.Index(fields=['occurred_on'], name='billing_bil_occurre_327c5c_idx')],
            },
        ),
    ]
