# Generated by Django 5.1.5 on 2026-05-16 17:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_enrollment_enrollment_unique_student_class_when_no_course'),
        ('quizzes', '0001_initial'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizAssignment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quizzes_assigned', to=settings.AUTH_USER_MODEL)),
                ('klass', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_assignments', to='academics.class')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='quizzes.quiz')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='schools.school')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['school', 'created_at'], name='quizzes_qui_school__350fe0_idx'), models.Index(fields=['school', 'student'], name='qa_school_student_idx'), models.Index(fields=['school', 'klass'], name='qa_school_klass_idx'), models.Index(fields=['school', 'quiz'], name='qa_school_quiz_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('klass__isnull', True), ('student__isnull', False)), models.Q(('klass__isnull', False), ('student__isnull', True)), _connector='OR'), name='assignment_exactly_one_target'), models.UniqueConstraint(condition=models.Q(('student__isnull', False)), fields=('quiz', 'student'), name='assignment_unique_per_student'), models.UniqueConstraint(condition=models.Q(('klass__isnull', False)), fields=('quiz', 'klass'), name='assignment_unique_per_class')],
            },
        ),
    ]
