# Generated by Django 5.1.5 on 2026-06-10 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_quiz_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='grade',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='quiz',
            name='section',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
