# Generated by Django 5.1.5 on 2026-06-13 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_answer_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='certificate_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
