# Generated by Django 5.1.5 on 2026-06-14 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_assigned_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ai_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
