# Generated by Django 5.1.5 on 2026-06-20 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_ai_enabled'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('schools', '0002_school_logo'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='non_admin_has_school',
        ),
        migrations.AddField(
            model_name='user',
            name='teacher_type',
            field=models.CharField(choices=[('SCHOOL', 'School Teacher'), ('SKILLSHIP', 'Skillship Teacher')], default='SCHOOL', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('role', 'MAIN_ADMIN'), ('school__isnull', False), models.Q(('role', 'TEACHER'), ('teacher_type', 'SKILLSHIP')), _connector='OR'), name='non_admin_has_school'),
        ),
    ]
