# Generated by Django 5.1.5 on 2026-06-21 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_user_non_admin_has_school_user_teacher_type_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('schools', '0002_school_logo'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='non_admin_has_school',
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('role', 'MAIN_ADMIN'), ('school__isnull', False), models.Q(('role', 'TEACHER'), ('teacher_type', 'SKILLSHIP')), ('role', 'SUB_ADMIN'), _connector='OR'), name='non_admin_has_school'),
        ),
    ]
