# Generated by Django 5.1.5 on 2026-06-27 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_subadmin_grants_from_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.TextField(blank=True),
        ),
    ]
