# Generated by Django 5.1.5 on 2026-05-25 18:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemoRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_name', models.CharField(max_length=200)),
                ('principal_name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('student_range', models.CharField(choices=[('up-to-250', 'Up to 250 students'), ('251-500', '251 to 500 students'), ('501-1000', '501 to 1000 students'), ('1000-plus', '1000+ students')], max_length=20)),
                ('phone_number', models.CharField(max_length=30)),
                ('email_address', models.EmailField(max_length=254)),
                ('school_board', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('CONVERTED', 'Converted'), ('LOST', 'Lost')], default='NEW', max_length=10)),
                ('triage_notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='leads_demo_status_cat_idx')],
            },
        ),
    ]
