# Generated by Django 5.1.5 on 2026-05-28 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demorequest',
            name='preferred_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demorequest',
            name='preferred_time_slot',
            field=models.CharField(blank=True, choices=[('10:30', '10:30 AM'), ('11:30', '11:30 AM'), ('12:30', '12:30 PM'), ('15:00', '3:00 PM'), ('16:00', '4:00 PM')], default='', max_length=10),
        ),
    ]
